# steps:
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "build",
#         "-t",
#         "southamerica-east1-docker.pkg.dev/microservices-dev-427010/image-register/orders-ms-prod",
#         "-f",
#         "dockerfile.prod",
#         "--platform=linux/amd64",
#         ".",
#       ]
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "push",
#         "southamerica-east1-docker.pkg.dev/microservices-dev-427010/image-register/orders-ms-prod",
#       ]
# options:
#   logging: 'CLOUD_LOGGING_ONLY'




steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-east1-docker.pkg.dev/test-propital/image-register/assets-ms -f dockerfile.prod --platform=linux/amd64 --build-arg POSTGRES_DB_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-east1-docker.pkg.dev/test-propital/image-register/assets-ms',
    ]
availableSecrets:
  secretManager:
  - versionName: projects/815111298774/secrets/POSTGRES_DB_URL/versions/1
    env: 'DATABASE_URL'
options:
  logging: 'CLOUD_LOGGING_ONLY'

